rootPath = ../../
experimentName=mhcHumanVariantsNsRemovedAndFiltered
include ../include.mk
heldOutSequences=NA12878 NA12891 NA12892 NA19238 NA19239 NA19240
theta = 0.00001
singleCopySpecies=NA12878 NA12892 NA19239 apd dbb mann nigerian qbl venter yanhuang NA12891 NA19238 NA19240 cox hg19 mcf panTro3 ssto watson

all : basic
